# Generated by Django 2.2.24 on 2021-11-01 20:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20211102_0139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewLike',
            new_name='Like',
        ),
    ]
