# Generated by Django 2.2.24 on 2021-11-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211102_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='total_likes',
        ),
    ]
